name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Garante que o deploy rode no push para a branch principal
  workflow_dispatch: # Permite a execução manual

permissions:
  # Permissão essencial para que o GITHUB_TOKEN possa fazer o commit na branch gh-pages
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: 2. Build & Deploy com Action Dedicada ao Angular
        # Esta Action é projetada para Angular e usa o angular-cli-ghpages internamente
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@latest 
        with:
          # Deve ser o caminho de saída (outputPath) do seu angular.json
          angular_dist_build_folder: dist/portfolio 
          
          # Seu base-href (conforme informado)
          base_href: /portfolio/ 
          
          # Configuração de build
          build_configuration: production 
          
          # O token é injetado automaticamente pelo GitHub
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          
          # A branch para onde a action irá fazer o deploy (o padrão do GitHub Pages)
          deploy_branch: gh-pages
